### PR TITLE
Added handling for MySqlConnector.MySqlDateTime objects

### LINKED ISSUE #97: MySqlConnector.MySqlDateTime is unhandled
I'll be working on this

### PR DESCRIPTION
**Pull request by wgawronIOL**
Fixes #97

### CODE REVIEW

**Comment by adriancs2** [comment]
thanks

**Comment by Trapulo** [comment]
Is this the fix for the error "Unhandled data type. Current processing data type: "MySqlConnector.MySqlDateTime" Please report this bug with this message to the development team."?

How can I apply it?

thanks

**Comment by wgawronIOL** [comment]
Currently, the fix hasn't made it into a build on NuGet. So you'll have to compile it yourself and reference that assembly in your project.
@adriancs2 Would you be able to upload a new version with this fix to NuGet?

**Comment by adriancs2** [comment]
Hi, the nuget package for this fix is released. Thanks all :)
https://www.nuget.org/packages/MySqlBackup.NET.MySqlConnector/

**Comment by adriancs2** [comment]
During the early days of writing this library for MySqlConnector, MySqlDateTime was not existed/implemented in MySqlConnector. That's why I commented out the section that handles MySqlDateTime in MySqlBackup.NET in the first place.

**Pull request merged**
